# Generated by Django 4.2.7 on 2023-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('marks1', models.IntegerField()),
                ('marks2', models.IntegerField()),
                ('marks3', models.IntegerField()),
                ('marks4', models.IntegerField()),
            ],
        ),
    ]
