# Generated by Django 4.2.7 on 2023-12-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='phone',
            new_name='mobile',
        ),
    ]
